[build]
builder = "NIXPACKS"
nixpacksConfigPath = "client/nixpacks.toml"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[static]
path = "dist" # Path to the output directory after building with Vite

[[static.routes]]
path = "/*" # Catch-all for routes
rewrite = "/index.html" # Redirect all non-static routes to index.html
