[static]
path = "dist" # Path to your build directory

[[static.routes]]
path = "/*" # Match all routes
rewrite = "/index.html" # Redirect to index.html

[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10