# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI, Build, and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  debug-env:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}

    steps:
      - run: echo $VITE_SUPABASE_URL
      - run: echo $VITE_SUPABASE_KEY
