# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI, Build, and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      
      - name: Install Packages (Client)
        working-directory: client/  
        run: npm ci
      - name: Install Packages (Server)
        working-directory: server/
        run: npm ci
      - name: Installing packages
        run: npm ci   
      

      - name: Run tests on client
        working-directory: client/
        run: npm test
      - name: Run tests on server
        working-directory: server/
        run: npm test


  lint-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Packages (Client)
        working-directory: client/
        run: npm ci
      - name: Install Packages (Server)
        working-directory: server/
        run: npm ci
      - name: Installing packages
        run: npm ci

      - run: npm run lint

      - name: Run build on client
        working-directory: client/
        run: npm run build

      - run: echo "Completed on ${{ matrix.node-version }}"