name: Validate Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "pre-deploy" ]]; then
            echo "Error: Pull requests to 'main' must originate from 'pre-deploy' branch."
            exit 1
          fi