name: Validate Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check if current branch is pre-deploy
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == "pre-deploy" ]]; then
            if [[ "${{ github.event.pull_request.base }}" != "main" ]] then
              echo "Error: Pull requests to 'main' must originate from 'pre-deploy' branch."
              exit 1
            fi
          fi